# Generated by Django 4.2.30 on 2026-07-16 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_projectstate_workspaceprojectstatesettings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectstate',
            name='group',
            field=models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='backlog', max_length=20),
        ),
        migrations.CreateModel(
            name='WorkspaceProjectLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='Project Label Name')),
                ('description', models.TextField(blank=True, verbose_name='Project Label Description')),
                ('color', models.CharField(blank=True, max_length=255, verbose_name='Project Label Color')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspace_project_labels', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Workspace Project Label',
                'verbose_name_plural': 'Workspace Project Labels',
                'db_table': 'workspace_project_labels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ProjectProjectLabel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_label_mappings', to='db.workspaceprojectlabel')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_labels', to='db.project')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Project Project Label',
                'verbose_name_plural': 'Project Project Labels',
                'db_table': 'project_project_labels',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='workspaceprojectlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('name', 'workspace'), name='project_label_unique_name_workspace_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='workspaceprojectlabel',
            unique_together={('name', 'workspace', 'deleted_at')},
        ),
        migrations.AddConstraint(
            model_name='projectprojectlabel',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('project', 'label'), name='project_project_label_unique_project_label_when_deleted_at_null'),
        ),
        migrations.AlterUniqueTogether(
            name='projectprojectlabel',
            unique_together={('project', 'label', 'deleted_at')},
        ),
    ]
