# Generated by Django 4.2.30 on 2026-07-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0124_alter_projectstate_group_workspaceprojectlabel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectprojectlabel',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_label_mappings', to='db.label'),
        ),
        migrations.DeleteModel(
            name='WorkspaceProjectLabel',
        ),
    ]
