# Generated by Django 4.2.30 on 2026-07-21 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0126_workspaceprojectlabelsettings_projectlabelproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomsettings',
            name='cycle_auto_complete',
            field=models.BooleanField(default=False),
        ),
    ]
