# Generated by Django 5.2.15 on 2026-08-14 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0122_alter_draftissue_assignees_alter_issue_assignees_and_more'),
        ('db', '0127_projectcustomsettings_cycle_auto_complete'),
    ]

    operations = [
    ]
