# Generated by Django 5.2.15 on 2026-08-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0128_merge_20260814_0443'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcustomsettings',
            name='auto_conventional_commit_labels',
            field=models.BooleanField(default=False),
        ),
    ]
